Repository Multiverse-of-Projects/NewsAI, pull requests merged in 2024-10, with the labels that each got.

#37 Added All Contributors Photos Issue #36
  .env.example
  .github/workflows/auto-assign.yaml
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted, gssoc-ext-24, level-1

#54 Update readme
  README.md
Labels: documentation, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, gssoc-ext-24, level1

#78 Update requirements file
  README.md
  requirements.txt
Labels: documentation, dependencies, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level1

#73 added greeting.yaml
  .github/workflows/greeting.yaml
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted, gssoc-ext, level2
